[project]
name = "Application django"
requires-python = "<4.0,>=3.10"
version = "1.0"
description = "Bienvenue sur le projet du Génialissime Victorio-Garcia"
authors = [
    {name = "Victorio Garcia", email = "victoriogarciapro@gmail.comr"}
]
maintainers = [
    {name = "Victorio Garcia", email = "victoriogarciapro@gmail.comr"}
]
readme = "README.md"
dependencies = [
    "django<6.0.0,>=5.1.4",
]

